apiVersion: cdi.kubevirt.io/v1beta1
kind: DataSource
metadata:
  name: win10-vdi
  namespace: openshift-virtualization-os-images
spec:
  source:
    pvc:
      name: win10-vdi
      namespace: openshift-virtualization-os-images