kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: rhel9-vdi
  labels:
    workload.template.kubevirt.io/desktop: 'true'
    app.kubernetes.io/part-of: hyperconverged-cluster
    template.kubevirt.io/version: v0.26.0
    app.kubernetes.io/version: 4.14.3
    template.kubevirt.io/type: vm
    vm.kubevirt.io/template: rhel9-desktop-large
    app.kubernetes.io/component: templating
    app.kubernetes.io/managed-by: ssp-operator
    os.template.kubevirt.io/rhel9.0: 'true'
    os.template.kubevirt.io/rhel9.1: 'true'
    app.kubernetes.io/name: custom-templates
    os.template.kubevirt.io/rhel9.2: 'true'
    flavor.template.kubevirt.io/large: 'true'
    os.template.kubevirt.io/rhel9.3: 'true'
    vm.kubevirt.io/template.namespace: openshift
  annotations:
    template.kubevirt.io/provider: ''
    template.kubevirt.io/provider-url: 'https://www.redhat.com'
    template.kubevirt.io/containerdisks: |
      registry.redhat.io/rhel9/rhel-guest-image
    template.kubevirt.io/version: v1alpha1
    openshift.io/display-name: Red Hat Enterprise Linux 9 VM
    openshift.io/documentation-url: 'https://github.com/kubevirt/common-templates'
    template.kubevirt.io/images: |
      https://access.redhat.com/downloads/content/479/ver=/rhel---9/9.0/x86_64/product-software
    operator-sdk/primary-resource-type: SSP.ssp.kubevirt.io
    defaults.template.kubevirt.io/disk: rootdisk
    name.os.template.kubevirt.io/rhel9.0: Red Hat Enterprise Linux 9.0 or higher
    name.os.template.kubevirt.io/rhel9.1: Red Hat Enterprise Linux 9.0 or higher
    template.kubevirt.io/editable: |
      /objects[0].spec.template.spec.domain.cpu.sockets
      /objects[0].spec.template.spec.domain.cpu.cores
      /objects[0].spec.template.spec.domain.cpu.threads
      /objects[0].spec.template.spec.domain.memory.guest
      /objects[0].spec.template.spec.domain.devices.disks
      /objects[0].spec.template.spec.volumes
      /objects[0].spec.template.spec.networks
    name.os.template.kubevirt.io/rhel9.2: Red Hat Enterprise Linux 9.0 or higher
    template.openshift.io/bindable: 'false'
    openshift.kubevirt.io/pronounceable-suffix-for-name-expression: 'true'
    operator-sdk/primary-resource: openshift-cnv/ssp-kubevirt-hyperconverged
    name.os.template.kubevirt.io/rhel9.3: Red Hat Enterprise Linux 9.0 or higher
    tags: 'hidden,kubevirt,virtualmachine,linux,rhel'
    template.kubevirt.io/provider-support-level: Full
    description: Template for Red Hat Enterprise Linux 9 VM or newer. A PVC with the RHEL disk image must be available.
    openshift.io/support-url: 'https://github.com/kubevirt/common-templates/issues'
    iconClass: icon-rhel
    openshift.io/provider-display-name: ''
objects:
  - apiVersion: kubevirt.io/v1
    kind: VirtualMachine
    metadata:
      annotations:
        vm.kubevirt.io/validations: |
          [
            {
              "name": "minimal-required-memory",
              "path": "jsonpath::.spec.domain.memory.guest",
              "rule": "integer",
              "message": "This VM requires more memory.",
              "min": 1610612736
            }
          ]
      labels:
        app: '${NAME}'
        kubevirt.io/dynamic-credentials-support: 'true'
        vm.kubevirt.io/template: rhel9-vdi
        vm.kubevirt.io/template.revision: '1'
        vm.kubevirt.io/template.namespace: 99-vdi
      name: '${NAME}'
    spec:
      dataVolumeTemplates:
        - apiVersion: cdi.kubevirt.io/v1beta1
          kind: DataVolume
          metadata:
            name: '${NAME}'
          spec:
            sourceRef:
              kind: DataSource
              name: '${DATA_SOURCE_NAME}'
              namespace: '${DATA_SOURCE_NAMESPACE}'
            storage:
              resources:
                requests:
                  storage: 30Gi
      running: false
      template:
        metadata:
          annotations:
            vm.kubevirt.io/flavor: large
            vm.kubevirt.io/os: rhel9
            vm.kubevirt.io/workload: desktop
          labels:
            kubevirt.io/domain: '${NAME}'
            kubevirt.io/size: large
        spec:
          domain:
            cpu:
              cores: 2
              sockets: 2
              threads: 1
            devices:
              disks:
                - disk:
                    bus: virtio
                  name: rootdisk
                - disk:
                    bus: virtio
                  name: cloudinitdisk
              inputs:
                - bus: virtio
                  name: tablet
                  type: tablet
              interfaces:
                - bridge: {}
                  model: virtio
                  name: default
              networkInterfaceMultiqueue: true
              rng: {}
            features:
              smm:
                enabled: true
            firmware:
              bootloader:
                efi: {}
            machine:
              type: pc-q35-rhel9.2.0
            memory:
              guest: 16Gi
          networks:
            - name: default
              multus:
                networkName: cnv-bridge
          terminationGracePeriodSeconds: 180
          volumes:
            - dataVolume:
                name: '${NAME}'
              name: rootdisk
            - cloudInitNoCloud:
                userData: |-
                  #cloud-config
                  user: cloud-user
                  password: ${CLOUD_USER_PASSWORD}
                  chpasswd: { expire: False }
                  rh_subscription:
                    activation-key: ocpv
                    org: 8054534
                  ssh_pwauth: true
                  packages:
                  - dnf-automatic
                  runcmd:
                  - systemctl enable --now dnf-automatic-install.timer
                  - bash -c 'echo "SELINUX=disabled" > /etc/selinux/config && echo "SELINUXTYPE=targeted" >> /etc/selinux/config && dnf -y install  https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm && dnf -y install dotnet-runtime-6.0 && dnf group install "Workstation" -y  && dnf -y install REPLACE_WITH_URL_OF_VDA_RPM && sudo systemctl set-default graphical.target && export CTX_XDL_NON_DOMAIN_JOINED=n && export CTX_XDL_AD_INTEGRATION=winbind && export CTX_XDL_DDC_LIST="REPLACE_WITH_DOMAIN_CONTROLLER_HOSTNAME" && export CTX_XDL_START_SERVICE=y && export CTX_XDL_REGISTER_SERVICE=y && export CTX_XDL_ADD_FIREWALL_RULES=y && export CTX_XDL_VDI_MODE=y && export CTX_XDL_DESKTOP_ENVIRONMENT=gnome && export CTX_EASYINSTALL_DNS=REPLACE_WITH_DNS_SERVER_IP && export CTX_EASYINSTALL_HOSTNAME=$(hostname) && export CTX_EASYINSTALL_NTPS=REPLACE_WITH_PINGABLE_NTP_SERVER && export CTX_EASYINSTALL_REALM=REPLACE_WITH_DOMAIN_REALM && export CTX_EASYINSTALL_FQDN=REPLACE_WITH_FQDN_OF_DOMAIN_CONTROLLER && export CTX_EASYINSTALL_USERNAME=domain_joiner && export CTX_EASYINSTALL_PASSWORD=Password && export CTX_EASYINSTALL_OU="REPLACE_WITH_MACHINE_OU" && /opt/Citrix/VDA/sbin/ctxinstall.sh -S && sed -i "s/^ *udp_preference_limit.*/udp_preference_limit = 10/g" /etc/krb5.conf && sudo reboot'
              name: cloudinitdisk
parameters:
  - name: NAME
    description: VM name
    generate: expression
    from: 'rhel9-vdi-[0-9]{3}'
  - name: DATA_SOURCE_NAME
    description: Name of the DataSource to clone
    value: rhel9
  - name: DATA_SOURCE_NAMESPACE
    description: Namespace of the DataSource
    value: openshift-virtualization-os-images
  - name: CLOUD_USER_PASSWORD
    description: Randomized password for the cloud-init user cloud-user
    value: password
    generate: expression
