kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: windows10-vdi
  labels:
    workload.template.kubevirt.io/desktop: 'true'
    app.kubernetes.io/part-of: hyperconverged-cluster
    template.kubevirt.io/version: v0.26.0
    app.kubernetes.io/version: 4.14.3
    template.kubevirt.io/type: vm
    vm.kubevirt.io/template: windows10-vdi
    app.kubernetes.io/component: templating
    app.kubernetes.io/managed-by: ssp-operator
    os.template.kubevirt.io/win10: 'true'
    app.kubernetes.io/name: custom-templates
    flavor.template.kubevirt.io/large: 'true'
    vm.kubevirt.io/template.namespace: openshift
  annotations:
    template.kubevirt.io/provider: ''
    template.kubevirt.io/provider-url: 'https://www.redhat.com'
    template.kubevirt.io/version: v1alpha1
    openshift.io/display-name: Microsoft Windows 10 VDI
    openshift.io/documentation-url: 'https://github.com/kubevirt/common-templates'
    operator-sdk/primary-resource-type: SSP.ssp.kubevirt.io
    name.os.template.kubevirt.io/win10: Microsoft Windows 10
    defaults.template.kubevirt.io/disk: rootdisk
    template.kubevirt.io/editable: |
      /objects[0].spec.template.spec.domain.cpu.cores
      /objects[0].spec.template.spec.domain.memory.guest
      /objects[0].spec.template.spec.domain.devices.disks
      /objects[0].spec.template.spec.volumes
      /objects[0].spec.template.spec.networks
    template.openshift.io/bindable: 'false'
    openshift.kubevirt.io/pronounceable-suffix-for-name-expression: 'true'
    operator-sdk/primary-resource: openshift-cnv/ssp-kubevirt-hyperconverged
    tags: 'hidden,kubevirt,virtualmachine,windows'
    defaults.template.kubevirt.io/network: default
    template.kubevirt.io/provider-support-level: Full
    description: Template for Microsoft Windows 10 VM. A PVC with the Windows disk image must be available.
    openshift.io/support-url: 'https://github.com/kubevirt/common-templates/issues'
    iconClass: icon-windows
    openshift.io/provider-display-name: ''
objects:
  - apiVersion: kubevirt.io/v1
    kind: VirtualMachine
    metadata:
      annotations:
        vm.kubevirt.io/validations: |
          [
            {
              "name": "minimal-required-memory",
              "path": "jsonpath::.spec.domain.memory.guest",
              "rule": "integer",
              "message": "This VM requires more memory.",
              "min": 2147483648
            }, {
              "name": "windows-virtio-bus",
              "path": "jsonpath::.spec.domain.devices.disks[*].disk.bus",
              "valid": "jsonpath::.spec.domain.devices.disks[*].disk.bus",
              "rule": "enum",
              "message": "virtio disk bus type has better performance, install virtio drivers in VM and change bus type",
              "values": ["virtio"],
              "justWarning": true
            }, {
              "name": "windows-disk-bus",
              "path": "jsonpath::.spec.domain.devices.disks[*].disk.bus",
              "valid": "jsonpath::.spec.domain.devices.disks[*].disk.bus",
              "rule": "enum",
              "message": "disk bus has to be either virtio or sata or scsi",
              "values": ["virtio", "sata", "scsi"]
            }, {
              "name": "windows-cd-bus",
              "path": "jsonpath::.spec.domain.devices.disks[*].cdrom.bus",
              "valid": "jsonpath::.spec.domain.devices.disks[*].cdrom.bus",
              "rule": "enum",
              "message": "cd bus has to be sata",
              "values": ["sata"]
            }
          ]
      labels:
        app: '${NAME}'
        vm.kubevirt.io/template: windows10-vdi
        vm.kubevirt.io/template.revision: '1'
        vm.kubevirt.io/template.namespace: 99-vdi
      name: '${NAME}'
      namespace: 99-vdi
    spec:
      dataVolumeTemplates:
        - apiVersion: cdi.kubevirt.io/v1beta1
          kind: DataVolume
          metadata:
            name: '${NAME}'
          spec:
            sourceRef:
              kind: DataSource
              name: '${DATA_SOURCE_NAME}'
              namespace: '${DATA_SOURCE_NAMESPACE}'
            storage:
              resources:
                requests:
                  storage: 60Gi
      running: false
      template:
        metadata:
          annotations:
            vm.kubevirt.io/flavor: large
            vm.kubevirt.io/os: windows10
            vm.kubevirt.io/workload: desktop
          labels:
            kubevirt.io/domain: '${NAME}'
            kubevirt.io/size: large
        spec:
          domain:
            clock:
              timer:
                hpet:
                  present: false
                hyperv: {}
                pit:
                  tickPolicy: delay
                rtc:
                  tickPolicy: catchup
              utc: {}
            cpu:
              cores: 2
              sockets: 2
              threads: 1
            devices:
              disks:
                - disk:
                    bus: virtio
                  name: rootdisk
                  bootOrder: 1
                - cdrom:
                    bus: sata
                  name: sysprep
                  bootOrder: 2
              inputs:
                - bus: usb
                  name: tablet
                  type: tablet
              interfaces:
                - bridge: {}
                  model: virtio
                  name: default
            features:
              acpi: {}
              apic: {}
              hyperv:
                reenlightenment: {}
                ipi: {}
                synic: {}
                synictimer:
                  direct: {}
                spinlocks:
                  spinlocks: 8191
                reset: {}
                relaxed: {}
                vpindex: {}
                runtime: {}
                tlbflush: {}
                frequencies: {}
                vapic: {}
            machine:
              type: pc-q35-rhel9.2.0
            memory:
              guest: 16Gi
          networks:
            - name: default
              multus:
                networkName: cnv-bridge
          terminationGracePeriodSeconds: 3600
          volumes:
            - dataVolume:
                name: '${NAME}'
              name: rootdisk
            - name: sysprep
              sysprep:
                configMap:
                  name: 'sysprep-config-${NAME}-jpkm41'
  - apiVersion: v1
    data:
      Unattend.xml: |
        <?xml version="1.0" encoding="utf-8"?>
        <unattend xmlns="urn:schemas-microsoft-com:unattend" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State">
          <settings pass="specialize">
            <component name="Microsoft-Windows-International-Core" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
              <InputLocale>0409:00000409</InputLocale>
              <SystemLocale>en-US</SystemLocale>
              <UILanguage>en-US</UILanguage>
              <UserLocale>en-US</UserLocale>
            </component>
            <component name="Microsoft-Windows-Shell-Setup" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
              <TimeZone>Eastern Standard Time</TimeZone>
              <ComputerName>${NAME}</ComputerName>
            </component>
            <component name="Microsoft-Windows-UnattendedJoin" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
              <Identification>
                <Credentials>
                  <Domain>REPLACE_WITH_DOMAIN_NAME</Domain>
                  <Password>REPLACE_WITH_DOMAINJOINER_PASSWORD</Password>
                  <Username>REPLACE_WITH_DOMAINJOINER_USER</Username>
                </Credentials>
                <JoinDomain>REPLACE_WITH_DOMAIN_NAME</JoinDomain>
                <DebugJoin>true</DebugJoin>
                <MachineObjectOU>REPLACE_WITH_MACHINE_OU</MachineObjectOU>
              </Identification>
            </component>
          </settings>
          <settings pass="oobeSystem">
            <component name="Microsoft-Windows-International-Core" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
              <InputLocale>0409:00000409</InputLocale>
              <SystemLocale>en-US</SystemLocale>
              <UILanguage>en-US</UILanguage>
              <UserLocale>en-US</UserLocale>
            </component>
            <component name="Microsoft-Windows-Shell-Setup" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
              <UserAccounts>
                <LocalAccounts>
                  <LocalAccount wcm:action="add">
                    <Name>VDIUser</Name>
                    <Group>Administrators</Group>
                    <Password>
                      <Value>password</Value>
                      <PlainText>True</PlainText>
                    </Password>
                  </LocalAccount>
                </LocalAccounts>
              </UserAccounts>
              <OOBE>
                <HideEULAPage>true</HideEULAPage>
                <HideLocalAccountScreen>true</HideLocalAccountScreen>
                <HideOnlineAccountScreens>true</HideOnlineAccountScreens>
                <HideWirelessSetupInOOBE>true</HideWirelessSetupInOOBE>
                <ProtectYourPC>3</ProtectYourPC>
                <NetworkLocation>Work</NetworkLocation>
                <SkipUserOOBE>true</SkipUserOOBE>
                <HideOEMRegistrationScreen>true</HideOEMRegistrationScreen>
              </OOBE>
              <TimeZone>Eastern Standard Time</TimeZone>
            </component>
          </settings>
        </unattend>
    kind: ConfigMap
    metadata:
      name: 'sysprep-config-${NAME}-jpkm41'
      ownerReferences: null
parameters:
  - name: NAME
    description: VM name
    generate: expression
    from: 'windows-[a-z0-9]{6}'
  - name: DATA_SOURCE_NAME
    description: Name of the DataSource to clone
    value: win10-vdi
  - name: DATA_SOURCE_NAMESPACE
    description: Namespace of the DataSource
    value: openshift-virtualization-os-images
